### ISSUE TITLE
Directed Graph/Nodes

### ISSUE THREAD

**Issue by ZeJackOfSpades** [ParisNeo/QGraphViz#11]
Hello I am looking for directed graph when linking 2 nodes.
Is there a way to have it ?
I have tried to set-up GraphType.DirectedGraph everywhere I can 

Thanks in advance for your help

**Comment by ParisNeo** [comment]
Thank you for the upgrade. I have added your name to the list of contributors.
I didn't have time lately to work on adding new features. I've accepted your pull request but I have to verify that we are still complient with the original GraphViz format so that when you export the graph it shows up correctly on other rendering tools.
