### ISSUE TITLE
Project description is contains bad data

### ISSUE THREAD

**Issue by asherf** [ParisNeo/QGraphViz#5]
<img width="1217" alt="Screen Shot 2020-03-30 at 1 17 22 PM" src="https://user-images.githubusercontent.com/1268088/77957744-cc7bb700-7288-11ea-86e3-e92be9848c7d.png">

https://pypi.org/project/QGraphViz/

Looked at setup.py, it looks fine... maybe there is an issue with the machine from which you build and upload the package to pypi ?

@ParisNeo

**Comment by ParisNeo** [comment]
Thank you for the remark. I didn't notice this.

I'm sorry for being late. I just got out of a corona virus infection episode that lasted for weeks. 

Now that I'm back to normal, I'll try to  repare this by uploading a new version of the code.

I had many update ideas to do, but unfortunately I was unable to do much the last few weeks.

**Comment by asherf** [comment]
@ParisNeo no worries.
Take care of yourself. feel better!

**Comment by benjyw** [comment]
@ParisNeo Glad you're getting better!

**Comment by ParisNeo** [comment]
Thank you all.

I did make a new update that added the possibility to extend the graph size automatically with two scrollbars.

Every thing is retro compatible. Normally, you just do pip install --upgrade qgraphviz and you'll have this new feature.

But still, the problem of the PYPi page is  mestirious. Maybe there is something wrong with the encoding of my README.md.

I'll try to cope with this issue when I have the time. I'm getting back to work and have a lot of things to do. Since it is just a cosmetic issue, I'll deal with it later.

Thanks for your support.

**Comment by ParisNeo** [comment]
I figured out the problem.
It comes from the autogenerator of README.md.
I replaced the page with a link to the github description.
I consider this issue closed.
Thank you All
